### ISSUE TITLE
Frame position not saved

### ISSUE THREAD

**Issue by hardvark** [GurliGebis/WoWAddon-PokemonTrainerNG#4] opened 2023-08-02 00:36 UTC
I love this addon. But for some time now you can move the frames using the scale option. The enemy team frame position is saved but the player team is always way out to the left when you leave and return to the game. Playing with scale slider puts it back where I had it.

**Comment by GurliGebis** [comment] 2024-04-30 09:27
This is a duplicate of #2, please refer to that ticket.

**Closed by GurliGebis** 2024-04-30 09:27 UTC
